### ISSUE TITLE
Misspelling in SAMAnalytical.RevitCheck

### ISSUE THREAD

**Issue by michalinadengusiak** [HoareLea/SAM_Revit#113]
**Describe the bug**

The word "match" was misspelt as "math" in the warning.

**Steps to recreate the bug**

Versions: Revit , Rhino

**Screenshots**

![image](https://user-images.githubusercontent.com/37042279/107126494-95b2fc00-68b0-11eb-8d7a-c1b86d4459a7.png)

**Test file**

**Comment by ZiolkowskiJakub** [comment]
Thanks
