### ISSUE TITLE
update to RhinoInside.Revit_0.9.7871.19806.msi

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM_Revit#136]
**Describe the bug**

**Steps to recreate the bug**

Versions: Revit , Rhino

**Screenshots**

![2021-07-21 08_56_17-Window](https://user-images.githubusercontent.com/26113670/126454231-155bbe8d-a2b3-4bdf-8867-79221d475618.png)

**Test file**

**Comment by ZiolkowskiJakub** [comment]
According to https://www.rhino3d.com/inside/revit/beta/reference/release-notes#v09 Rhino/Grasshopper needs to be updated to version 7.8.21196.5001

**Comment by ZiolkowskiJakub** [comment]
Update Implementation https://github.com/HoareLea/SAM_Revit/tree/RhinoUpdate

**Comment by michaldengusiak** [comment]
awaiting McNeel support

**Comment by michaldengusiak** [comment]
solved in Revit.Rhino Inside 1.0.7884.17134, was caused by custom W3 node
