### ISSUE TITLE
bug SAMobjectFromRevit

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM_Revit#2]
1. Does not work for the linked model, add capability
![image](https://user-images.githubusercontent.com/26113670/72475457-d5f59700-37e2-11ea-9acf-6106716a10f6.png)

2. allow to get Space from Room - Name and LocationPoint

**Comment by ZiolkowskiJakub** [comment]
Creating SAM Panels from RevitLinkedModel:

![image](https://user-images.githubusercontent.com/16777757/72526951-7ee1d780-385f-11ea-9b4c-afd604f72ebf.png)

**Comment by michaldengusiak** [comment]
tested and approved
