### ISSUE TITLE
add Revit 2021 support 

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM_Revit#70]
**Describe the solution you'd like**

to test process add Revit 2021
**Additional context**

**Comment by ZiolkowskiJakub** [comment]
Added. 

Comments:
RhinoInside.Revit may cause issues here. Waiting for RhinoInside.Revit Nuget package for full migration

**Comment by michaldengusiak** [comment]
ok this works fine for this specific version, however we need to adjust way to deal with multiple versions

![image](https://user-images.githubusercontent.com/26113670/87537091-fd45f780-c691-11ea-9fe5-2a33be7f3bb5.png)

**Comment by michaldengusiak** [comment]
ok this is now implemented thanks to @kike for advice
using .ghlink
![image](https://user-images.githubusercontent.com/26113670/90502349-8f379900-e145-11ea-87c4-dc414d70ba4d.png)
